/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.enterprisesearch.deep;import cn.zhuatech.enterprisesearch.model.AuditLog;import cn.zhuatech.enterprisesearch.repository.AuditLogRepository;import jakarta.persistence.*;import jakarta.validation.constraints.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;import java.time.*;import java.util.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Service @Transactional(readOnly=true) public class DeepDomainService{private final EntityManager em;private final AuditLogRepository logs;/**
                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                            */
public DeepDomainService(EntityManager e,AuditLogRepository l){em=e;logs=l;}/**
                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                        */
public Dashboard dashboard(String o){return new Dashboard(sources(o),documents(o),queryCount(o));}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public SourceView source(SourceRequest r){var s=new KnowledgeSource(r.organizationCode(),r.sourceCode(),r.name(),r.sourceType());em.persist(s);audit("SEARCH_SOURCE","登记知识源",s.sourceCode,s.sourceType);return view(s);}/**
                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                         */
@Transactional public SourceView activate(Long id){var s=source(id);if(!"DRAFT".equals(s.status))throw conflict("只有草稿知识源可以启用");s.status="ACTIVE";audit("SEARCH_SOURCE","启用知识源",s.sourceCode,s.name);return view(s);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public DocumentView index(Long sourceId,DocumentRequest r){var s=source(sourceId);if(!"ACTIVE".equals(s.status))throw conflict("知识源未启用");if(!r.contentHash().matches("[a-fA-F0-9]{64}"))throw bad("内容摘要必须为64位SHA-256");if("PRIVATE".equals(r.visibility())&&(blank(r.allowedUsers())&&blank(r.allowedGroups())))throw bad("私有文档必须配置用户或用户组权限");var d=new IndexedDocument(sourceId,s.organizationCode,r.externalId(),r.title(),r.content(),r.contentHash().toLowerCase(),r.visibility(),normalize(r.allowedUsers()),normalize(r.allowedGroups()));em.persist(d);s.lastIndexedAt=LocalDateTime.now();audit("SEARCH_INDEX","索引知识文档",r.externalId(),r.title());return view(d,s.sourceCode);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public SearchResponse search(SearchRequest r){var docs=em.createQuery("select d from IndexedDocument d where d.organizationCode=:o and d.status='INDEXED'",IndexedDocument.class).setParameter("o",r.organizationCode()).getResultList();Set<String> groups=split(r.groups());String key=r.keyword().toLowerCase();List<SearchHit> hits=docs.stream().filter(d->allowed(d,r.userKey(),groups)).map(d->hit(d,key)).filter(h->h.score()>0).sorted(Comparator.comparingInt(SearchHit::score).reversed()).limit(20).toList();String queryId="Q-"+UUID.randomUUID();em.persist(new SearchQueryLog(queryId,r.organizationCode(),r.userKey(),r.keyword(),hits.size()));String context=hits.stream().limit(3).map(h->"["+h.citation()+"] "+h.snippet()).reduce((a,b)->a+"\n"+b).orElse("");audit("SEARCH_QUERY","执行权限搜索",queryId,"results="+hits.size());return new SearchResponse(queryId,hits,context);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public FeedbackView feedback(FeedbackRequest r){var q=em.createQuery("select q from SearchQueryLog q where q.queryId=:id and q.userKey=:u",SearchQueryLog.class).setParameter("id",r.queryId()).setParameter("u",r.userKey()).getResultStream().findFirst().orElse(null);if(q==null)throw bad("查询记录不存在或不属于当前用户");var d=em.find(IndexedDocument.class,r.documentId());if(d==null||!d.organizationCode.equals(q.organizationCode))throw bad("反馈文档不属于查询组织");var f=new SearchFeedback(r.queryId(),r.documentId(),r.userKey(),r.relevant(),r.comment());em.persist(f);audit("SEARCH_FEEDBACK","记录检索反馈",r.queryId(),"relevant="+r.relevant());return new FeedbackView(f.id,f.queryId,f.documentId,f.userKey,f.relevant,f.commentText,f.createdAt);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
@Transactional public DocumentView retire(Long id){var d=document(id);d.status="RETIRED";var s=source(d.sourceId);audit("SEARCH_INDEX","下线知识文档",d.externalId,d.title);return view(d,s.sourceCode);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private boolean allowed(IndexedDocument d,String user,Set<String> groups){if("ORG".equals(d.visibility))return true;if(split(d.allowedUsers).contains(user))return true;var permitted=split(d.allowedGroups);return groups.stream().anyMatch(permitted::contains);}/**
                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                     */
private SearchHit hit(IndexedDocument d,String key){String title=d.title.toLowerCase(),content=d.contentText.toLowerCase();int score=(title.contains(key)?10:0)+(content.contains(key)?5:0);if(score==0){for(String token:key.split("\\s+"))if(token.length()>1)score+=(title.contains(token)?3:0)+(content.contains(token)?1:0);}String snippet=d.contentText.length()>160?d.contentText.substring(0,160)+"…":d.contentText;var s=source(d.sourceId);return new SearchHit(d.id,d.title,s.sourceCode+"#"+d.externalId,snippet,score,d.visibility);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private Set<String>split(String v){if(blank(v))return Set.of();return new HashSet<>(Arrays.stream(v.split(",")).map(String::trim).filter(x->!x.isBlank()).toList());}/**
                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                       */
private String normalize(String v){return blank(v)?"":String.join(",",split(v));}/**
                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                        */
private boolean blank(String v){return v==null||v.isBlank();}/**
                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                     */
private List<SourceView>sources(String o){return em.createQuery("select s from KnowledgeSource s where s.organizationCode=:o order by s.createdAt desc",KnowledgeSource.class).setParameter("o",o).getResultList().stream().map(this::view).toList();}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
private List<DocumentView>documents(String o){return em.createQuery("select d from IndexedDocument d where d.organizationCode=:o order by d.indexedAt desc",IndexedDocument.class).setParameter("o",o).setMaxResults(100).getResultList().stream().map(d->view(d,source(d.sourceId).sourceCode)).toList();}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
private long queryCount(String o){return em.createQuery("select count(q) from SearchQueryLog q where q.organizationCode=:o",Long.class).setParameter("o",o).getSingleResult();}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     */
private KnowledgeSource source(Long id){var x=em.find(KnowledgeSource.class,id);if(x==null)throw missing("知识源不存在");return x;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
private IndexedDocument document(Long id){var x=em.find(IndexedDocument.class,id);if(x==null)throw missing("知识文档不存在");return x;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
private void audit(String m,String a,String n,String d){logs.save(new AuditLog(m,a,n,"search-domain",d));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
private ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
private ResponseStatusException conflict(String m){return new ResponseStatusException(HttpStatus.CONFLICT,m);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
private ResponseStatusException missing(String m){return new ResponseStatusException(HttpStatus.NOT_FOUND,m);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private SourceView view(KnowledgeSource s){return new SourceView(s.id,s.organizationCode,s.sourceCode,s.name,s.sourceType,s.status,s.lastIndexedAt);}/**
                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                       */
private DocumentView view(IndexedDocument d,String sourceCode){return new DocumentView(d.id,d.sourceId,sourceCode,d.externalId,d.title,d.contentHash,d.visibility,d.allowedUsers,d.allowedGroups,d.status,d.indexedAt,d.version);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 public record SourceRequest(@NotBlank String organizationCode,@NotBlank String sourceCode,@NotBlank String name,@NotBlank String sourceType){}/**
                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                */
public record DocumentRequest(@NotBlank String externalId,@NotBlank String title,@NotBlank String content,@NotBlank String contentHash,@Pattern(regexp="ORG|PRIVATE")String visibility,String allowedUsers,String allowedGroups){}/**
                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                  */
public record SearchRequest(@NotBlank String organizationCode,@NotBlank String userKey,String groups,@NotBlank String keyword){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
public record FeedbackRequest(@NotBlank String queryId,@NotNull Long documentId,@NotBlank String userKey,boolean relevant,String comment){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */
public record SourceView(Long id,String organizationCode,String sourceCode,String name,String sourceType,String status,LocalDateTime lastIndexedAt){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
public record DocumentView(Long id,Long sourceId,String sourceCode,String externalId,String title,String contentHash,String visibility,String allowedUsers,String allowedGroups,String status,LocalDateTime indexedAt,long version){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
public record SearchHit(Long documentId,String title,String citation,String snippet,int score,String visibility){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         */
public record SearchResponse(String queryId,List<SearchHit>hits,String answerContext){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
public record FeedbackView(Long id,String queryId,Long documentId,String userKey,boolean relevant,String comment,LocalDateTime createdAt){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
public record Dashboard(List<SourceView>sources,List<DocumentView>documents,long queryCount){}
}
