/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.enterprisesearch.deep;import cn.zhuatech.enterprisesearch.common.ApiResponse;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                   * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                   */
@RestController @RequestMapping("/api/admin/search-ops") public class DeepAdminController{private final DeepDomainService s;/**
                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                               */
public DeepAdminController(DeepDomainService s){this.s=s;}/**
                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                         */
@PostMapping("/sources/{id}/activate")ApiResponse<?> activate(@PathVariable Long id){return ApiResponse.ok(s.activate(id));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     */
@PostMapping("/documents/{id}/retire")ApiResponse<?> retire(@PathVariable Long id){return ApiResponse.ok(s.retire(id));}}
