/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.enterprisesearch.deep;import jakarta.persistence.*;import java.time.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="es_knowledge_sources",uniqueConstraints=@UniqueConstraint(columnNames={"organizationCode","sourceCode"})) class KnowledgeSource{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Column(nullable=false,length=40)String organizationCode;@Column(nullable=false,length=50)String sourceCode;@Column(nullable=false,length=120)String name;@Column(nullable=false,length=40)String sourceType;@Column(nullable=false,length=20)String status="DRAFT";LocalDateTime lastIndexedAt;LocalDateTime createdAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
protected KnowledgeSource(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
KnowledgeSource(String o,String c,String n,String t){organizationCode=o;sourceCode=c;name=n;sourceType=t;createdAt=LocalDateTime.now();}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="es_documents",uniqueConstraints=@UniqueConstraint(columnNames={"sourceId","externalId"})) class IndexedDocument{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Version long version;@Column(nullable=false)Long sourceId;@Column(nullable=false,length=40)String organizationCode;@Column(nullable=false,length=80)String externalId;@Column(nullable=false,length=200)String title;@Lob @Column(nullable=false)String contentText;@Column(nullable=false,length=64)String contentHash;@Column(nullable=false,length=20)String visibility;@Column(length=1000)String allowedUsers;@Column(length=1000)String allowedGroups;@Column(nullable=false,length=20)String status="INDEXED";LocalDateTime indexedAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 */
protected IndexedDocument(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
IndexedDocument(Long s,String o,String e,String t,String c,String h,String v,String u,String g){sourceId=s;organizationCode=o;externalId=e;title=t;contentText=c;contentHash=h;visibility=v;allowedUsers=u;allowedGroups=g;indexedAt=LocalDateTime.now();}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="es_query_logs",uniqueConstraints=@UniqueConstraint(columnNames="queryId")) class SearchQueryLog{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Column(nullable=false,length=60)String queryId;@Column(nullable=false,length=40)String organizationCode;@Column(nullable=false,length=80)String userKey;@Column(nullable=false,length=300)String keyword;int resultCount;LocalDateTime searchedAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                      */
protected SearchQueryLog(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
SearchQueryLog(String q,String o,String u,String k,int c){queryId=q;organizationCode=o;userKey=u;keyword=k;resultCount=c;searchedAt=LocalDateTime.now();}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="es_feedback",uniqueConstraints=@UniqueConstraint(columnNames={"queryId","documentId","userKey"})) class SearchFeedback{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Column(nullable=false,length=60)String queryId;@Column(nullable=false)Long documentId;@Column(nullable=false,length=80)String userKey;boolean relevant;@Column(length=300)String commentText;LocalDateTime createdAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                */
protected SearchFeedback(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
SearchFeedback(String q,Long d,String u,boolean r,String c){queryId=q;documentId=d;userKey=u;relevant=r;commentText=c;createdAt=LocalDateTime.now();}}
