/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.enterprisesearch;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.http.MediaType;import org.springframework.test.web.servlet.*;import java.util.regex.*;import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.httpBasic;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@SpringBootTest @AutoConfigureMockMvc class DeepSearchOpsTests{@Autowired MockMvc mvc;String hash="aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Test void searchReturnsCitationAndRespectsAcl()throws Exception{long s=activeSource("SRC-1");index(s,"DOC-PUB","采购审批制度","采购金额超过十万元需要总经理审批","ORG","","");index(s,"DOC-SEC","薪酬调整制度","薪酬调整仅限人力资源部门查看","PRIVATE","","hr");post("/api/search-ops/search","{\"organizationCode\":\"ZH-SH\",\"userKey\":\"alice\",\"groups\":\"sales\",\"keyword\":\"审批\"}").andExpect(jsonPath("$.data.hits.length()").value(1)).andExpect(jsonPath("$.data.hits[0].citation").value("SRC-1#DOC-PUB"));post("/api/search-ops/search","{\"organizationCode\":\"ZH-SH\",\"userKey\":\"hr-user\",\"groups\":\"hr\",\"keyword\":\"薪酬\"}").andExpect(jsonPath("$.data.hits.length()").value(1));}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Test void inactiveSourceAndPrivateDocumentWithoutAclAreBlocked()throws Exception{long s=source("SRC-2");post("/api/search-ops/sources/"+s+"/documents",doc("D-X","知识","内容","ORG","","")).andExpect(status().isConflict());admin("/api/admin/search-ops/sources/"+s+"/activate","{}");post("/api/search-ops/sources/"+s+"/documents",doc("D-PRIVATE","机密","机密内容","PRIVATE","","")).andExpect(status().isBadRequest());}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Test void feedbackMustBelongToQueryUser()throws Exception{long s=activeSource("SRC-3");long d=index(s,"DOC-3","设备操作手册","设备启动前检查安全联锁","ORG","","");MvcResult q=post("/api/search-ops/search","{\"organizationCode\":\"ZH-SH\",\"userKey\":\"bob\",\"groups\":\"ops\",\"keyword\":\"设备\"}").andReturn();String query=stringField(q,"queryId");post("/api/search-ops/feedback","{\"queryId\":\""+query+"\",\"documentId\":"+d+",\"userKey\":\"mallory\",\"relevant\":true,\"comment\":\"越权反馈\"}").andExpect(status().isBadRequest());post("/api/search-ops/feedback","{\"queryId\":\""+query+"\",\"documentId\":"+d+",\"userKey\":\"bob\",\"relevant\":true,\"comment\":\"结果准确\"}").andExpect(status().isOk());}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 long source(String n)throws Exception{return id(post("/api/search-ops/sources","{\"organizationCode\":\"ZH-SH\",\"sourceCode\":\""+n+"\",\"name\":\"企业文档中心\",\"sourceType\":\"DOCUMENT\"}").andReturn());}/**
                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                            */
long activeSource(String n)throws Exception{long s=source(n);admin("/api/admin/search-ops/sources/"+s+"/activate","{}");return s;}/**
                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                              */
long index(long s,String e,String t,String c,String v,String u,String g)throws Exception{return id(post("/api/search-ops/sources/"+s+"/documents",doc(e,t,c,v,u,g)).andReturn());}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
String doc(String e,String t,String c,String v,String u,String g){return "{\"externalId\":\""+e+"\",\"title\":\""+t+"\",\"content\":\""+c+"\",\"contentHash\":\""+hash+"\",\"visibility\":\""+v+"\",\"allowedUsers\":\""+u+"\",\"allowedGroups\":\""+g+"\"}";}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
ResultActions post(String u,String b)throws Exception{return mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post(u).with(httpBasic("operator","operator123")).contentType(MediaType.APPLICATION_JSON).content(b));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
ResultActions admin(String u,String b)throws Exception{return mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post(u).with(httpBasic("admin","admin123")).contentType(MediaType.APPLICATION_JSON).content(b));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 */
long id(MvcResult r)throws Exception{var m=Pattern.compile("\"id\":(\\d+)").matcher(r.getResponse().getContentAsString());Assertions.assertTrue(m.find());return Long.parseLong(m.group(1));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
String stringField(MvcResult r,String f)throws Exception{var m=Pattern.compile("\""+f+"\":\"([^\"]+)\"").matcher(r.getResponse().getContentAsString());Assertions.assertTrue(m.find());return m.group(1);}}
